nav:
  Home: /
  About: /about/
  My Work: /archives/
  

projects_url: https://github.com/hellooben/hellooben.github.io

customize:
    gravatar:
        email: 
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/android-chrome-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: http://github.com/probberechts/cactus-dark
        twitter: https://twitter.com/_helloben
        instagram: https://instagram.com/_helloben
        facebook: https://www.facebook.com/ben.bailey.5895
        linkedin: https://www.linkedin.com/in/ben-bailey-823407137/
    show_all_posts: false
    post_count: 5
    highlight: rainbow

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-86660611-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
